# Generated by Django 3.1.2 on 2020-10-29 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_abtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.CharField(max_length=10000)),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.CharField(max_length=10000)),
                ('target', models.CharField(max_length=128)),
                ('ml_algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_used', to='endpoints.mlalgorithm')),
            ],
        ),
    ]
